### ISSUE TITLE
节点正常，小火箭显示延迟，但是不能上网

### ISSUE THREAD

**Issue by Simonaorg** [pennyMorant/zeropanel#7]
搭建的vemss，电脑端正常使用，但是小火箭虽然显示延迟数据，打不开网页和刷新
另，服务器卸载xtayR , 后台仍保留该节点数据，电脑端延迟正常显示-1，小火箭仍有延迟数据而不是超时。

**Comment by pennyMorant** [comment]
能不能连通和使用，都是后端控制的与前端无关
